### ISSUE TITLE
Feedback! 

### ISSUE THREAD

**Issue by CaioGH** [cpaivaj/talking-data-ad-tracking-fraud-detection#1]
Curti bastante!

Eu sugiro 2 edições de informação:

1. Trocar o HTML abaixo para R.

![image](https://user-images.githubusercontent.com/26192893/95107980-02ef2e80-0711-11eb-84c4-e7f9454b8415.png)

2. Deixe claro o uso do R e do modelo de RandomForest no readme do repositório/projeto.  Isso ajuda quem está estudando/pesquisando sobre o assunto  ;)

**Comment by cpaivaj** [comment]
> Curti bastante!
> 
> Eu sugiro 2 edições de informação:
> 
> 1. Trocar o HTML abaixo para R.
> 
> ![image](https://user-images.githubusercontent.com/26192893/95107980-02ef2e80-0711-11eb-84c4-e7f9454b8415.png)
> 
> 1. Deixe claro o uso do R e do modelo de RandomForest no readme do repositório/projeto.  Isso ajuda quem está estudando/pesquisando sobre o assunto  ;)

Oi, valeu pelo feedback.

Sobre o HTML, ficou com esse ícone porque fiz um relatório em HTML aí o github identificou como um projeto com mais conteúdo em HTML por causa do relatório.
Sobre o README, realmente faltou explicar o conteúdo do projeto, obrigado pelo toque.
:D

**Comment by CaioGH** [comment]
Realmente, eu percebi o html depois... Isso pesou o projeto como se HTML fosse o foco né :/

Tmj, sucesso!
